[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma generate']

[start]
cmd = 'node simple-server.js'

[variables]
NODE_ENV = 'production'